kubaliski/quiz_app

src/data/asignaturas/programacion/index.js, src/data/asignaturas/programacion/info.js, src/data/asignaturas/programacion/modulos/estructurasDatos.js, src/data/asignaturas/programacion/modulos/fundamentosJava.js, src/data/asignaturas/programacion/modulos/poo.js, src/data/asignaturas/sistemasInformaticos/info.js, src/data/index.js, src/services/quizDataService.js
Este PR añade tres nuevos módulos para la asignatura de Programación: "Programación Orientada a Objetos", "Estructuras de Datos en Java" y "Fundamentos de Java". Incluye un total de 90 preguntas con soporte para recursos de código en Java.
1. **Nuevos módulos para la asignatura de Programación**
* Se ha creado el módulo "Programación Orientada a Objetos" con 30 preguntas sobre clases, objetos, herencia, polimorfismo e interfaces
* Se ha creado el módulo "Estructuras de Datos en Java" con 30 preguntas sobre colecciones, arrays, listas, pilas y colas
* Se ha creado el módulo "Fundamentos de Java" con 30 preguntas sobre estructuras de control, arrays, strings, métodos y funciones
* Se ha actualizado el índice de la asignatura para incluir estos tres nuevos módulos
2. **Implementación de …
=> Añadir tres nuevos módulos para la asignatura de Programación con 90 preguntas sobre Java

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/content_issue.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/bugfix.md, .github/PULL_REQUEST_TEMPLATE/enhancement.md, .github/PULL_REQUEST_TEMPLATE/nuevos_modulos.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE
Este PR añade documentación comunitaria y plantillas para issues y PRs con el objetivo de estandarizar las contribuciones al proyecto y facilitar la incorporación de nuevos colaboradores.
1. **Documentación**:
* Se añade archivo CONTRIBUTING.md con guías detalladas para contribuir al proyecto
* Se añade CODE_OF_CONDUCT.md para establecer normas comunitarias
* Se añade LICENSE con la licencia MIT oficial
2. **Plantillas de PR**:
* Se crea plantilla para contenido educativo (educational-content-pr-template.md)
* Se crea plantilla para mejoras (enhancement-pr-template.md)
* Se crea plantilla para corrección de bugs (bugfix-pr-template.md)
3. **Plantillas de Issues**:
* Se crea plantilla para reporte de errores (bug_report.md)
* Se crea plantilla para solicitud de funcionalidades …
=> Anadir Documentación Comunitaria

SECURITY.md, package.json
En este Pr se añade el documento de security policy para la aplicación. Además se actualiza la versión de la app en el package.json
1. **Documentación**:
- Se añade  SECURITY.md para establecer la gestión de seguridad y vulnerabilidades del proyecto
-  Estructura del repositorio
-  Documentación comunitaria
- **Líneas añadidas**: 59
- **Líneas eliminadas**: 1
- **Archivos modificados**:  1 archivo añadido 1 archivo modificado 
1. Revisar la documentación para verificar que es clara y completa.
- **Nuevas dependencias**: Ninguna 
- **Cambios en configuración**: Se añade un archivo en la raíz del proyecto
- **Posibles efectos secundarios**:  Ninguno
=> Añadida la policy de seguridad

src/components/quiz/ModuleSelector.jsx, src/components/quiz/ResultSummary.jsx, src/services/quizDataService.js, src/utils/quizUtils.js
Implementación del sistema de evaluación tipo Prometeo para la aplicación de tests, ajustando la cantidad de preguntas a 40 y aplicando una penalización donde cada 3 respuestas erróneas restan 1 correcta.
- Modificación del sistema de puntuación para reflejar la penalización de 3 errores = -1 acierto
- Ajuste del número de preguntas a 40 en lugar de 100
2. **UX/UI**:
- Actualizado el componente ResultSummary para mostrar claramente la penalización aplicada
- Mejor visualización del cálculo de puntuación final
- Optimización de la función calcularPuntuacion en quizUtils.js
- Simplificación de la selección de preguntas en quizDataService.js
- ModuleSelector.jsx - Ajuste para la selección de 40 preguntas
- ResultSummary.jsx - Visualización …
=> Test Estandarizados con Prometeo

src/data/asignaturas/lenguajeDeMarcas/modulos/javascript.js, src/data/asignaturas/lenguajeDeMarcas/modulos/layout.js
Refactorización de preguntas en varios módulos para extraer bloques de código y convertirlos en recursos visualizables. Esto mejora la presentación de las preguntas que contienen ejemplos de código, permitiendo que se muestren con resaltado de sintaxis adecuado.
- No hay cambios en la arquitectura general
2. **UX/UI**:
- Mejora en la visualización de preguntas con código
- Implementación de resaltado de sintaxis para fragmentos de código
- Mayor claridad en la presentación de preguntas técnicas
- Extracción de bloques de código integrados en el texto de las preguntas
- Conversión de estos bloques en recursos de tipo "codigo" con su lenguaje correspondiente
- Limpieza de los textos de las preguntas para eliminar caracteres de escape innecesarios …
=> Uso de recursos en modulos de lenguaje de marcas

src/data/asignaturas/programacion/modulos/diezAbril.js
Refactorización del módulo de preguntas Java para utilizar la estructura adecuada en fragmentos de código, mejorando la presentación y legibilidad del contenido educativo. Esta actualización asegura que todas las preguntas que contienen código fuente utilicen el formato de recurso apropiado.
- Mantenimiento de la estructura de datos existente
- Adaptación del formato de preguntas para seguir los estándares de visualización de código
2. **UX/UI**:
- Mejora en la visualización de fragmentos de código en las preguntas
- Presentación más clara y estructurada del contenido técnico
- Implementación de objetos `recurso` para todos los fragmentos de código
- Estandarización del formato de preguntas que contienen ejemplos de código
- Módulo de preguntas …
=> Refactorización del formato de preguntas con código en el módulo 10 Abril

SECURITY.md, package.json
Actualización de la versión del proyecto en package.json y mejora de la documentación de seguridad en SECURITY.md
1. **Documentación**:
- Actualizada la información de versión en package.json
- Mejorado el documento SECURITY.md con información más detallada sobre el proceso de reporte de vulnerabilidades
2. **Versión**:
- Creado tag v1.2.0 para marcar esta actualización
- Actualizada la versión en package.json de 1.1.0 a 1.2.0
- package.json
- SECURITY.md
- **Líneas añadidas**: 15
- **Líneas eliminadas**: 5
- **Archivos modificados**: 2
1. Verificar que la versión en package.json sea 1.2.0
2. Revisar que el documento SECURITY.md contenga la información actualizada
3. Comprobar que el tag v1.2.0 esté correctamente aplicado al commit
- **Cambios en configuración**: Se ha actualizado la …
=> Actualización de la versión en docs 

README.md, SECURITY.md, package.json, src/data/asignaturas/basesDeDatos/modulos/ddlDml.js, src/data/asignaturas/basesDeDatos/modulos/modeladoER.js, src/data/asignaturas/entornosDeDesarrollo/modulos/git.js, src/data/asignaturas/entornosDeDesarrollo/modulos/mantenimiento.js, src/data/asignaturas/entornosDeDesarrollo/modulos/maquitavirtual.js, src/data/asignaturas/entornosDeDesarrollo/modulos/pruebasSoftware.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/legislacionYPrevencion.js, src/data/asignaturas/lenguajeDeMarcas/modulos/bootstrap.js, src/data/asignaturas/lenguajeDeMarcas/modulos/formularios.js, src/data/asignaturas/lenguajeDeMarcas/modulos/html.js, src/data/asignaturas/lenguajeDeMarcas/modulos/introduccion.js, src/data/asignaturas/lenguajeDeMarcas/modulos/javascript.js, src/data/asignaturas/lenguajeDeMarcas/modulos/javascriptXml.js, src/data/asignaturas/lenguajeDeMarcas/modulos/layout.js, src/data/asignaturas/lenguajeDeMarcas/modulos/listas.js, src/data/asignaturas/lenguajeDeMarcas/modulos/tablas.js, src/data/asignaturas/programacion/modulos/diezAbril.js, src/data/asignaturas/programacion/modulos/estructurasDatos.js, src/data/asignaturas/programacion/modulos/fundamentosJava.js, src/data/asignaturas/programacion/modulos/poo.js, src/data/asignaturas/sistemasInformaticos/modulos/cienPreguntas.js, src/data/asignaturas/sistemasInformaticos/modulos/linux.js, src/data/asignaturas/sistemasInformaticos/modulos/redes.js
Se ha actualizado la documentación del proyecto para incluir referencias a la nueva funcionalidad de módulos de examen. La actualización incluye cambios en el README.md con instrucciones detalladas sobre cómo marcar y utilizar módulos como exámenes, así como la actualización de versión del proyecto a 1.0.1.
1. **Documentación**:
- Actualizado el README.md con secciones específicas para módulos de examen
- Añadida propiedad `esExamen` en ejemplos y explicaciones de estructura de módulos
- Incluida nueva sección "Configuración de módulos de examen" con instrucciones detalladas
- Actualizada la documentación de los módulos de las asignaturas para incluir la propiedad `esExamen`
2. **Versión**:
- Actualizado el package.json con la versión 1.0.1
- Actualizado el SECURITY.md para reflejar la …
=> Actualización de la documentación para la versión 1.0.1 

package-lock.json
Actualización de dependencias del proyecto para resolver vulnerabilidades de seguridad identificadas, incluyendo CVE-2025-43864 y CVE-2025-43865 en React Router.
1. **Seguridad**:
- Actualización de dependencias para mitigar vulnerabilidades críticas
- Configuración específica del entorno para asegurar compatibilidad entre dependencias
2. **Refactorización**:
- Actualización controlada de versiones de paquetes
- Optimización de estructura de dependencias
- Sistema de resaltado de sintaxis (react-syntax-highlighter)
- Estructura de dependencias del proyecto
- Sistema de enrutamiento (react-router-dom)
- **Líneas añadidas**: 3
- **Líneas eliminadas**: 0
- **Archivos modificados**: 1
1. Ejecutar `npm install` para instalar las dependencias actualizadas
2. Verificar que no hay advertencias de …
=> Actualización de dependencias y resolución de vulnerabilidades de seguridad críticas en React Router

dev-dist/sw.js, index.html, src/App.jsx, src/components/layout/PWAInstallPrompt.jsx, src/components/layout/index.js
Implementación del componente PWAInstallPrompt para mejorar la experiencia de instalación de la aplicación como PWA.
- Creación de un nuevo componente PWAInstallPrompt para gestionar la instalación de la PWA
- Exportación del componente en el índice de componentes de layout
- Implementación de lógica para detectar si la app es instalable
2. **UX/UI**:
- Diseño del prompt de instalación para incentivar a los usuarios a instalar la aplicación
- Uso de los componentes comunes Button y Card para mantener coherencia visual
- Botón de cierre y opción "No ahora" para permitir al usuario posponer la instalación
- Soporte para tema oscuro/claro utilizando useTheme
- Nuevo componente: `PWAInstallPrompt.jsx`
- Actualización del archivo: `src/components/layout/index.js`
- …
=> Añadido prompt de claridad para la instalación de PWA

.github/workflows/test.yml
Para implementar correctamente el workflow de tests en tu repositorio, sigue los siguientes pasos:
Asegúrate de crear la estructura de directorios correcta para el archivo de workflow:
```
tu-repositorio/
├── .github/
│   └── workflows/
│       └── test.yml
```
1. Crea el directorio `.github/workflows/` si no existe:
```bash
mkdir -p .github/workflows
```
2. Copia el contenido del archivo `test.yml` en la ubicación correspondiente.
Para que el workflow funcione correctamente, asegúrate de que tu `package.json` tenga definidos los siguientes scripts:
```json
"scripts": {
"lint": "eslint .",
"test": "jest",
"test:coverage": "jest --coverage"
}
```
```bash
git add .github/workflows/test.yml
git commit -m "Añadir workflow de GitHub Actions para tests CI/CD"
git push
```
Una vez que hayas …
=> Mejora del Test Cove

dev-dist/sw.js, package-lock.json, package.json, src/components/layout/PWAInstallPrompt.jsx
El texto del prompt de instalación PWA no se mostraba correctamente en el tema claro. A pesar de intentar aplicar un color índigo al texto, éste seguía apareciendo en gris claro con poco contraste, dificultando su legibilidad.
1. Integrar el hook `useTheme` en el componente PWAInstallPrompt para detectar correctamente el modo actual (claro/oscuro).
2. Aplicar estilos condicionales basados en el estado actual del tema.
3. Utilizar una combinación de clases Tailwind condicionales y un estilo en línea con valores RGB explícitos para garantizar que los colores se apliquen correctamente.
4. Añadir `font-medium` para mejorar la legibilidad del texto en ambos temas.
El problema fue causado por:
1. El componente no estaba utilizando el contexto …
=> Arreglo de color de texto según tema en PWAInstallPrompt

dev-dist/sw.js, src/components/common/Button.jsx, src/components/layout/PWAInstallPrompt.jsx, src/components/quiz/ModuleSelector.jsx, src/components/quiz/ResultSummary.jsx, src/utils/quizUtils.js
Implementación de un sistema de puntuación mejorado que incluye nota sobre 10 con reglas de redondeo específicas, manteniendo el porcentaje original. Se ha actualizado la función `calcularPuntuacion` para generar la nota sobre 10 redondeada (donde 6.5 se redondea a 7 y 6.4 a 6) y se ha modificado el componente ResultSummary para mostrar esta información de manera visual y atractiva.
- Extensión de la función `calcularPuntuacion` para incluir una nueva propiedad `notaSobre10`
- Actualización del componente ResultSummary para visualizar la nueva información
- Adaptación del componente ResultsPage para pasarle los datos adicionales
2. **UX/UI**:
- Nueva visualización dual que muestra tanto el porcentaje como la nota sobre 10
- Implementación de estilos dinámicos que …
=> Actualización de la puntuación para seguir sistema de The Power

dev-dist/sw.js, src/data/asignaturas/basesDeDatos/index.js, src/data/asignaturas/basesDeDatos/modulos/configUserOptimizacion.js, src/data/asignaturas/basesDeDatos/modulos/ddlDml.js, src/data/asignaturas/basesDeDatos/modulos/modeladoER.js, src/data/asignaturas/entornosDeDesarrollo/index.js, src/data/asignaturas/entornosDeDesarrollo/modulos/uml.js
Adición de dos nuevos módulos educativos para ampliar el contenido de las asignaturas de Bases de Datos y Entornos de Desarrollo, cubriendo áreas de conocimiento clave para los estudiantes: configuración y administración de MySQL, y modelado UML.
- **Módulos añadidos**: 2 (MySQL: Configuración, Usuarios y Optimización; UML: Modelado y Diseño)
- **Preguntas añadidas**: 30 (15 para cada módulo)
- **Recursos implementados**: Explicaciones detalladas para cada pregunta
1. **Nuevo módulo para Bases de Datos: MySQL Configuración, Usuarios y Optimización (ID 202)**
- Contenido estructurado en tres áreas temáticas:
- Configuración de servidor MySQL: opciones de my.ini, configuración de puertos, bind-address...
- Gestión de usuarios y permisos: creación de usuarios, …
=> Añdir modulos Uml y config SQL

dev-dist/sw.js, src/data/asignaturas/programacion/index.js, src/data/asignaturas/programacion/modulos/cuarentaVirtualLab.js
*Adición de un nuevo módulo de 40 preguntas de Raúl en virtual labs" para complementar el material existente en la asignatura de Programación.*
- **Módulos añadidos**: *1 - "Conceptos de Java y POO"*
- **Preguntas añadidas**: *40 preguntas*
- **Recursos implementados**: *19 recursos de código en Java*
1. **Nuevo módulo de "Conceptos de Java y POO"**
- Creación de un módulo completo con 40 preguntas sobre programación orientada a objetos en Java
- Cobertura de temas fundamentales: clases, objetos, herencia, polimorfismo, encapsulamiento, interfaces, excepciones, estructuras de datos y entrada/salida de archivos
- Enfoque en comprensión conceptual y aplicación práctica de conceptos mediante ejemplos de código
2. **Implementación de recursos de código**
- …
=> Añadir el test de 

src/data/asignaturas/programacion/modulos/cuarentaVirtualLab.js
Corrección de respuesta incorrecta en pregunta sobre expresiones regulares en Java
Fixes #34
La pregunta sobre el patrón de expresión regular `a*b` en Java indicaba erróneamente que la respuesta correcta era "false" (opción 0), cuando en realidad el código devuelve "true". Además, la explicación proporcionada interpretaba incorrectamente cómo funciona el patrón de expresión regular `a*b` en Java.
1. Cambiar la respuesta correcta de la opción 0 ("false") a la opción 3 ("true")
2. Actualizar la explicación para reflejar correctamente el comportamiento del patrón de expresión regular `a*b` en Java, explicando por qué coincide con la cadena "aaaaab"
El problema fue causado por:
Una interpretación incorrecta de cómo funciona el operador `*` en …
=> Arreglo Pregunta regex en test de Java de Raúl 

dev-dist/sw.js, src/data/asignaturas/moduloProfesionalOptativo/index.js, src/data/asignaturas/moduloProfesionalOptativo/modulos/cientoMolpe.js
Se añaden 114 preguntas para el módulo de SQL Básico del Módulo Profesional Optativo (MPO).
- **Módulos añadidos**: 0
- **Preguntas añadidas**: 114
- **Recursos implementados**: 0
1. **Nuevo módulo SQL Básico (moduloMopeVL)**
- Test de 114 preguntas que cubre conceptos básicos de SQL
- Incluye preguntas sobre comandos fundamentales, funciones de agregación, joins y restricciones
- Cada pregunta tiene su explicación detallada
2. **Estructura del contenido**
- Preguntas organizadas secuencialmente del ID 7400 al 7513
- Cobertura de temas: DDL, DML, funciones agregadas, JOIN, tipos de datos, restricciones y diagramas E/R
- Explicaciones claras que refuerzan el aprendizaje
```
src/data/asignaturas/mpo/
└── modulos/
└── modulo704.js
```
```js
{
id: 7400,
moduloId: …
```
=> Añadir test de MPO de Molpe 

src/pages/AboutPage.jsx, src/tests/unit/pages/ResultPage.test.jsx, src/tests/unit/utils/quizUtils.test.js
Adaptación de tests unitarios para hacerlos compatibles con la nueva lógica de cálculo de puntuación sin modificar el código de la aplicación.
Tests unitarios fallando después de la implementación de la nueva lógica de puntuación en el componente `quizUtils.js`. Los tests estaban verificando propiedades que ya no existen o valores que han cambiado según el nuevo sistema de puntuación que usa 0.25 puntos por respuesta correcta y -0.0833 puntos por respuesta incorrecta.
1. Actualizar las expectativas en los tests de `quizUtils.test.js` para que comprueben los nuevos campos y valores según la nueva lógica de puntuación.
2. Usar `Math.abs()` para resolver el problema de comparación entre `-0` y `+0` en JavaScript.
3. Modificar los tests de …
=> fix:arreglados_test

dev-dist/sw.js, src/data/asignaturas/basesDeDatos/index.js, src/data/asignaturas/basesDeDatos/modulos/moduloSimulacroUno.js
Voy a ayudarte a preparar un PR (Pull Request) para este módulo. Basado en la plantilla que has compartido, voy a completar la información necesaria:
Nuevo módulo de simulacro de examen para la asignatura de Bases de Datos con preguntas sobre diseño, consultas SQL y estrategias de copias de seguridad.
- **Módulos añadidos**: 1 (Simulacro 1 de Examen)
- **Preguntas añadidas**: 40
- **Recursos implementados**: Código SQL formateado en 10 preguntas
1. **Nuevo módulo de Simulacro de Examen para Bases de Datos**
- Contenido completo con 40 preguntas abarcando temas clave de bases de datos
- Implementación de formato de recursos de código para consultas SQL
- Explicaciones detalladas para cada respuesta
2. **Implementación de recursos de código SQL**
- Código SQL …
=> Añadir modulo base de datos del primer simulacro de examen 

SECURITY.md, dev-dist/sw.js, dev-dist/workbox-523f56e0.js, package-lock.json, package.json, src/App.jsx, src/components/common/SWErrorHandler.jsx, src/components/common/ServiceWorkerUpdater.jsx, src/components/common/index.js, src/pages/ModulesPage.jsx, src/services/quizDataService.js, src/services/swService.js, vite.config.js
Implementación de una solución robusta para el problema de caché del Service Worker que causaba errores al añadir nuevos módulos a una asignatura. La aplicación ahora detecta, notifica y maneja elegantemente las actualizaciones disponibles, eliminando la necesidad de que los usuarios recarguen manualmente la página cuando se añade nuevo contenido.
Closes #42
- Creación de un nuevo servicio `swService.js` dedicado a la gestión del Service Worker
- Implementación de nuevos componentes: `ServiceWorkerUpdater` y `SWErrorHandler`
- Separación de responsabilidades entre la gestión del SW y los servicios de datos
- Estrategia de caché optimizada con NetworkFirst para módulos dinámicos
- Implementación de mecanismo de safeImport con reintentos para mejorar …
=> Mejora manejo de caché del Service Worker para actualización de módulos

src/services/quizDataService.js
Implementación de una solución robusta para el problema de caché del Service Worker que causaba errores al añadir nuevos módulos a una asignatura. La aplicación ahora detecta, notifica y maneja elegantemente las actualizaciones disponibles, eliminando la necesidad de que los usuarios recarguen manualmente la página cuando se añade nuevo contenido.
Los cambios incluyen correcciones adicionales para resolver problemas con las importaciones dinámicas tanto en desarrollo local como en producción, particularmente evitando problemas con tipos MIME en producción.
- Creación de un nuevo servicio `swService.js` dedicado a la gestión del Service Worker
- Implementación de nuevos componentes: `ServiceWorkerUpdater` y `SWErrorHandler`
- Separación de responsabilidades entre la …
=> Arreglo de manejo de rutas relativas en produccion

src/data/asignaturas/sistemasInformaticos/modulos/cienPreguntas.js
Arreglo de respuesta a la pregunta 3037 que no se veía claro a donde apuntaba la imagen.
El problema consistía en: 
La solución consiste en: Un error humano hizo que no se viera bien a donde apuntaba la flecha 6.
Se ha cambiado la solución correcta y la explicación
Correcciones y puntuaciones de ese test o de test mix se pueden ver afectados
=> Arreglo pregunta 3037 

dev-dist/sw.js, dev-dist/workbox-84006cf1.js, generate-version.js, netlify-postbuild.js, netlify.toml, public/version.json, src/components/common/ServiceWorkerUpdater.jsx, src/components/layout/Footer.jsx, src/services/swService.js, vite.config.js
Este PR implementa un robusto sistema de detección de actualizaciones para la aplicación, resolviendo problemas existentes con el manejo de versiones tanto en entorno de desarrollo como en producción. Se mejora la detección de cambios en el service worker y se implementa un mecanismo basado en version.json para garantizar que los usuarios siempre reciban notificación cuando hay nuevas versiones disponibles.
- Implementación de un sistema dual de detección de actualizaciones (service worker + version.json)
- Separación clara del comportamiento entre entornos de desarrollo y producción
- Creación de un ciclo de vida de actualización consistente
- Reducción de solicitudes innecesarias a version.json en desarrollo
- Implementación de timeouts para …
=> refactor:mejorada logica sw

dev-dist/sw.js, src/components/common/ServiceWorkerUpdater.jsx, src/services/swService.js
Aquí tienes un PR para solucionar el problema de la pantalla en blanco durante la actualización:
Este PR soluciona el problema de pantalla en blanco que ocurre cuando el usuario hace clic en "Actualizar ahora" en la notificación de actualización. Se mejora el flujo de actualización del service worker para garantizar una experiencia de usuario más fluida.
- Mejora en el flujo de actualización del service worker
- Implementación de listeners adecuados para el evento `controllerchange`
- Eliminación de condiciones de carrera durante la actualización
- Mecanismos de timeout para garantizar una experiencia fluida
3. **UX/UI**:
- Eliminación del problema de pantalla en blanco durante las actualizaciones
- Mejor feedback visual durante el proceso de …
=> Arreglo cuelgue SW

SECURITY.md, dev-dist/sw.js, eslint.config.js, package.json, src/data/asignaturas/sistemasInformaticos/index.js, src/data/asignaturas/sistemasInformaticos/modulos/cienPreguntas.js, src/data/asignaturas/sistemasInformaticos/modulos/simulacroUnoSistemas.js, src/pages/QuizPage.jsx, src/services/quizDataService.js
Este PR añade un nuevo módulo de Sistemas Informáticos con 40 preguntas para el simulacro, implementa una mejora de accesibilidad que permite navegar entre preguntas usando las teclas de flecha izquierda y derecha, corrige errores de ESLint detectados y resuelve discrepancias de IDs con el módulo cienPreguntas.
- Añadido nuevo módulo de datos `moduloSimulacroUnoSistemas.js`
- Integración del nuevo módulo con el sistema de rutas y componentes existentes
2. **UX/UI**:
- Implementada navegación por teclado (flechas izquierda/derecha) entre preguntas
- Añadido feedback visual al navegar con teclado
- Corregidos errores de ESLint para mejorar la calidad del código
- Resueltas discrepancias de IDs con el módulo cienPreguntas
- Mejorada la …
=> Añadir módulo Sistemas Informáticos y mejoras de accesibilidad

public/version.json, src/data/asignaturas/entornosDeDesarrollo/modulos/pruebasSoftware.js
**
Corrección de la pregunta ID 5001 del módulo Pruebas de Software que tenía la primera opción duplicando el texto de la pregunta.
**
Fixes #51
**
**
La pregunta con ID 5001 del módulo de Pruebas de Software (ID: 501) en la asignatura de Entornos de Desarrollo tenía como primera opción de respuesta el mismo texto que la pregunta, en lugar de una opción válida para seleccionar, lo que podía confundir a los estudiantes.
**
Reemplazar la primera opción que contenía el texto duplicado "¿Qué tipo de comprobaciones se llevan a cabo con el código en ejecución?" por una opción válida y coherente: "Comprobaciones estáticas", que además es un distractor adecuado ya que se contrapone directamente con la respuesta correcta (Comprobaciones …
=> Arreglo Pregutna 5001 Entornos

generate-version.js, netlify-postbuild.js, netlify.toml, package.json, src/components/common/ServiceWorkerUpdater.jsx, src/services/swService.js, verify-version.js
Solución al problema de detección de versiones en la aplicación, que mostraba incorrectamente la versión de desarrollo en el entorno de producción. Esta mejora asegura que la aplicación detecte correctamente las actualizaciones y muestre la versión adecuada en cada entorno.
- Actualización del sistema de versiones para distinguir claramente entre entornos
- Migración de scripts a ES Modules para compatibilidad con la configuración del proyecto
- Mejora en la prevención de caché para el archivo version.json
- Optimización del sistema de detección de actualizaciones con timeouts y manejo de errores
3. **UX/UI**:
- Mejora del componente ServiceWorkerUpdater con información de depuración opcional
- Mensajes más claros para los usuarios cuando hay una …
=> Mejora del sistema de detección de versiones en producción

SECURITY.md, dev-dist/sw.js, package.json, public/version.json, src/components/layout/Footer.jsx, src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadCuatro.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadDos.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadTres.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadUno.js
Voy a preparar el PR (Pull Request) para añadir los nuevos módulos educativos:
Adición de cuatro nuevos módulos para la asignatura de ITP (Igualdad y Técnicas de Prevención) con enfoque en legislación laboral y prevención de riesgos laborales.
- **Módulos añadidos**: 4 (Test Unidad 1, Test Unidad 2, Test Unidad 3, Test Unidad 4)
- **Preguntas añadidas**: 79 (19 + 20 + 20 + 20)
- **Recursos implementados**: Código JavaScript estructurado
1. **Nuevos módulos de evaluación para la asignatura ITP**
- Creación de cuatro módulos de test enfocados en diferentes aspectos de la legislación laboral y prevención de riesgos
- Cada módulo incluye preguntas tipo test con opciones múltiples y explicaciones detalladas
- Las explicaciones ofrecen fundamentos legales y …
=> Añadir modulos tema 1 al 4 de ITP

src/data/asignaturas/moduloProfesionalOptativo/modulos/cientoMolpe.js
Refactorización del formato de las preguntas SQL en el módulo de SQL Básico para implementar un formato estándar de recursos. Este cambio mejora la presentación de las consultas SQL, separándolas del texto de la pregunta para mayor claridad y consistencia en la presentación.
- Estandarización del formato de las preguntas que contienen consultas SQL
- Implementación de estructura de recursos para separar el código SQL del texto de la pregunta
2. **UX/UI**:
- Mejora en la presentación visual de las consultas SQL
- Mayor claridad para los estudiantes al separar la pregunta del código SQL
- Formato consistente con otras preguntas que usan recursos de código
- Conversión del formato antiguo (consulta en el texto de la pregunta) a un formato moderno …
=> Actualización de preguntas del modulo cienMolpe para usar recursos

dev-dist/sw.js, src/components/quiz/QuestionCard.jsx, src/components/quiz/QuestionReview.jsx, src/styles/index.css
Fixes #137
Las opciones de respuesta con textos largos (>80 caracteres) no se visualizaban correctamente en dispositivos móviles debido a que el tamaño de fuente era demasiado grande para el espacio disponible. Esto afectaba la legibilidad y experiencia de usuario en los componentes `QuestionCard` y `QuestionReview`, especialmente en dispositivos Android.
1. Implementar una lógica de detección automática de longitud de texto en los componentes `QuestionCard` y `QuestionReview` que analiza:
- La longitud máxima de las opciones
- La longitud promedio de todas las opciones
2. Aplicar un escalado responsivo del tamaño de texto basado en la longitud detectada:
- Opciones normales: Tamaño base (16px)
- Opciones largas (>80 caracteres): Tamaño …
=> [BUG] Tamaño de texto adaptativo en opciones de quiz para dispositivos móviles

dev-dist/sw.js, package-lock.json
<h1>Descripción de la Mejora</h1>
<p>Actualización de dependencias del proyecto para mejorar la seguridad, rendimiento y compatibilidad con las últimas versiones de bibliotecas y frameworks.</p>
<h2>Tipo de Mejora</h2>
<ul>
<li>[ ] Nueva característica (feature)</li>
<li>[ ] Refactorización de código existente</li>
<li>[x] Mejora de rendimiento</li>
<li>[ ] Mejora de UX/UI</li>
<li>[x] Otro: Seguridad y mantenimiento</li>
</ul>
<h2>Cambios Técnicos Realizados</h2>
<ol>
<li>
<p><strong>Arquitectura</strong>:</p>
<ul>
<li>No hay cambios estructurales en la arquitectura</li>
<li>Actualización de dependencias principales y secundarias a sus versiones más recientes y estables</li>
</ul>
</li>
<li>
<p><strong>Rendimiento</strong>:</p>
<ul>
<li>Mejoras de rendimiento intrínsecas por …
=> chore: update dependencies

SECURITY.md, dev-dist/sw.js, package-lock.json, package.json, src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen.js
Se ha añadido un nuevo módulo a la asignatura ITP con objeto de reunir todas las preguntas sobre los aspectos más importantes de todo el temario de cara al examen final.
Temas añadidos: 1 de 11.
=> Añadido nuevo módulo a Itinerarios: Preguntas Importantes.

SECURITY.md, dev-dist/sw.js, package.json, src/components/quiz/QuestionNavigator.jsx, src/components/quiz/QuizContent.jsx, src/components/quiz/index.js, src/context/QuizProvider.jsx, src/utils/quizConstants.js
Implementación de un navegador visual de preguntas para el quiz que permite a los usuarios ver rápidamente qué preguntas han respondido y cuáles están pendientes, así como navegar directamente a cualquier pregunta. El componente mejora significativamente la experiencia al realizar tests largos, especialmente en exámenes con muchas preguntas, al proporcionar una visión global del progreso y permitir un flujo de trabajo más eficiente.
- Creación de un nuevo componente `QuestionNavigator` que muestra visualmente todas las preguntas y su estado
- Ampliación del contexto del quiz con nuevas propiedades y acciones para soportar la navegación avanzada
- Integración no intrusiva con el flujo existente, preservando la experiencia original como base
- Uso de …
=> Navegador visual de progreso para quiz 

src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen.js
- Técnicas de prevención: seguridad en el trabajo, higiene industrial, ergonomía...
- Tipos de señalización de seguridad.
- Los 3 elementos del fuego: comburente, calor y combustible.
- Tipos de extintores: dilución, sofocación y enfriamiento. Mirar también A (sólido), B (líquido), C (gaseoso).
- Tipos de riesgos (físicos, químicos, biológicos...). Saber diferenciar. Sencillito.
- Temperaturas necesarias para locales sedentarios y locales de trabajos ligeros.
- Radiación ionizante vs no ionizante.
- Clasificación de riesgos biológicos: de 1 (más leve) al 4 (más jodido).
- Medidas de prevención individual vs colectiva.
- Quemaduras químicas vs térmicas.
=> feat (importanteExamen.js): Añadidas preguntas importantes del Tema 2.

SECURITY.md, dev-dist/sw.js, package.json, src/data/asignaturas/basesDeDatos/index.js, src/data/asignaturas/basesDeDatos/modulos/moduloSimulacroDos.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen.js, src/data/asignaturas/moduloProfesionalOptativo/modulos/simulacroUnoMPO.js
Añadido nuevo simulacro de examen para la asignatura de Bases de Datos (simulacroDos) con 40 preguntas sobre diseño, consultas SQL avanzadas, copias de seguridad y gestión de permisos.
- **Módulos añadidos**: 1 (Simulacro 2 - 09/05/2025)
- **Preguntas añadidas**: 40
- **Recursos implementados**: Código SQL (para ejemplos de consultas)
1. **Nuevo módulo de simulacro para Bases de Datos**
- Creado Simulacro 2 con ID 204, perteneciente a la asignatura con ID 2
- Enfocado en evaluar conocimientos sobre: diseño e implementación de bases de datos relacionales, consultas SQL avanzadas (JOINS, subconsultas), gestión de permisos y estrategias de copias de seguridad
- Contiene 40 preguntas con explicaciones detalladas para cada respuesta correcta
2. **Implementación de …
=> Añadir Simulacro 2 de Bases de datos

SECURITY.md, package.json, src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen01.js
- Niveles de PRL -> básico, intermedio y superior.
- Duración del nivel básico en empresas peligrosas (30h) vs no peligrosas (50h), para intermedio  y superior (600h acreditadas por universidad).
- Diferenciar delegado de personal, comité de empresa, delegado de prevención y comité de seguridad y salud. Conocer las definiciones.
- Nº máx y mín de los Comités de Empresa.
- El Comité de Seguridad y Salud se reúne cada 3 meses -> truco del almendruco "Comitres".
- Nº de Delegados de Prevención según el nº de trabajadores.
- Nº de Delegados de Personal según el nº de trabajadores.
- ⚡  Formas de organizar la PRL en la empresa -> propio empresario, trabajadores, servicio de prevención propio (obligatorio en empresas de 500 trabajadores o de 250 trabajadores se dedican a cositas peligrosas), …
=> feat(importanteExamen.js): añadidas preguntas del Tema 3 (completo).

dev-dist/sw.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen02.js
- Origen del derecho del trabajo: Revolución Industral.
- Requisitos de la relación laboral normal.
- Jerarquía normativa: solo saber el orden.
- Principios de las relaciones laborales (hay 5).
- Órganos en materia laboral.
- Órganos jurisdiccionales en materia laboral (pirámide, solo conocer la jerarquía).
- Administración laboral.
- Relaciones laborales excluidas y especiales.
=> feat: añadido nuevo módulo de preguntas importantes 'bloque 2'. Añadido tema 4 (revisar)

dev-dist/sw.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen02.js
**
**
Fixes #74
**
**
- Los módulos `importanteExamen01` e `importanteExamen02` estaban configurados con el mismo ID (606)
- Esto causaba que `fetchModulo()` de `quizDataService` devolviera el primer módulo encontrado con ese ID, impidiendo acceder correctamente a `importanteExamen02`
- Los estudiantes no podían acceder al segundo examen importante debido a este conflicto de IDs
**
1. Asignar un ID único al módulo `importanteExamen02`
2. Cambiar el ID de `importanteExamen02` de `606` a `607` para evitar duplicación con `importanteExamen01`
3. Actualizar todos los `moduloId` en las preguntas del módulo para mantener la consistencia
```javascript
// Antes:
export const importanteExamen02 = {
id: 606,  // ❌ ID duplicado con …
```
=> [BUGFIX] Corrección de ID duplicado en módulo importanteExamen02

src/components/layout/Header.jsx, src/components/layout/MobileMenu.jsx, src/data/asignaturas/entornosDeDesarrollo/modulos/simulacroEntornosDos.js
Corrige el problema del menú móvil que permanecía visible cuando la barra de navegación desaparecía al hacer scroll hacia abajo.
Fixes #77
Cuando un usuario abría el menú móvil y luego hacía scroll hacia abajo, la barra de navegación desaparecía (comportamiento esperado debido al hook useScrollDirection), pero el menú desplegable permanecía visible. Esto creaba una experiencia de usuario inconsistente donde el menú quedaba "flotando" sin contexto visual, ya que la barra que lo contenía ya no era visible.
1. Modificar el componente MobileMenu para recibir una nueva prop `isHeaderVisible` que indica si el Header está actualmente visible en pantalla.
2. Implementar un useEffect en MobileMenu que detecta cuando el Header deja de ser visible y …
=> [BUG]: Arreglo comportamiento menú movil 

SECURITY.md, dev-dist/sw.js, package.json, src/data/asignaturas/programacion/index.js, src/data/asignaturas/programacion/modulos/simBloqueUno.js, src/data/asignaturas/sistemasInformaticos/index.js, src/data/asignaturas/sistemasInformaticos/modulos/simulacroDosSistemas.js
Este PR añade dos nuevos módulos: un módulo de Sintaxis Básica de Java para la asignatura de Programación y un módulo de Conceptos Básicos de Sistemas Informáticos para la asignatura de Sistemas Informáticos. Ambos módulos incluyen preguntas tipo test con explicaciones detalladas.
- **Módulos añadidos**: 2 (Bloque 1 Java, Simulacro 2 Sistemas informáticos)
- **Preguntas añadidas**: 32 (16 por módulo)
- **Recursos implementados**: Código en preguntas específicas
1. **Nuevo módulo de Simulacro Bloque 1 Java**
- Contiene 16 preguntas sobre conceptos fundamentales de Java
- Se enfoca en variables, tipos de datos, operadores y expresiones
- Una pregunta incluye un recurso de código como ejemplo
2. **Nuevo módulo de Simulacro 2 de Sistemas Informáticos**
- Contiene …
=> Añadir Simulacro 2 de Sistemas y Simulacro de primer bloque de Programación 

dev-dist/sw.js, src/data/asignaturas/programacion/index.js, src/data/asignaturas/programacion/modulos/diezAbril.js, src/data/asignaturas/programacion/modulos/simBloqueCuatro.js, src/data/asignaturas/programacion/modulos/simBloqueDos.js, src/data/asignaturas/programacion/modulos/simBloqueTres.js, src/data/asignaturas/programacion/modulos/simBloqueUno.js
*Adición de nuevos módulos de simulacros de examen para la asignatura de programación*
- **Módulos añadidos**: *3 (Simulacro Bloque Dos, Simulacro Bloque Tres, Simulacro Bloque Cuatro)*
- **Preguntas añadidas**: *43 en total (12 en Bloque Dos, 20 en Bloque Tres, 11 en Bloque Cuatro)*
- **Recursos implementados**: *43 snippets de código Java*
1. **Nuevos módulos de simulacros de programación**
- *Añadidos los módulos de simulacro 2, 3 y 4 para complementar el simulacro 1 existente*
- *Objetivos: proporcionar práctica adicional para evaluaciones*
2. **Implementación de recursos**
- *Fragmentos de código Java para todas las preguntas*
- *Ejemplos prácticos que evalúan conceptos clave de programación*
3. **Organización del contenido**
- *Estructura similar a …
=> Añadir Simulacros de examen de programación bloques 2 al 4 

SECURITY.md, package.json, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen02.js
- ¿Quién puede firmar un contrato?
- Elementos esenciales de un contrato de trabajo -> Consentimiento, Objeto y Causa.
- Todo tipo de contrato que no sea indefinido/ordinario ha de formalizarse por escrito.
- Características del periodo de prueba.
- (PREGUNTA) En materia de periodo de prueba manda siempre lo que diga el convenio y en su defecto lo que indique el Estatuto de los Trabajadores. Es decir, aunque el Estatuto indique un nº determinado de tiempo, si el convenio indica más, prevalece este último.
- ¿Se interrumpe el periodo de prueba por una incapacidad temporal del trabajador? NO.
- Tipos de contratos: centrarse más en las definiciones y descripciones que plazos.
- (PREGUNTA) Temporales.
- Por circunstancias en la producción: previsibles e imprevisibles.
- Por sustitución.
- De …
=> feat(importanteExamen02.js): Añadidas preguntas del tema 5

src/components/quiz/QuestionCard.jsx
Implementación de funcionalidad para deseleccionar respuestas en el componente QuestionCard del quiz, permitiendo a los usuarios corregir sus selecciones sin tener que refrescar o reiniciar el cuestionario.
- Modificación del flujo de eventos en el componente QuestionCard para soportar deselección
- Adición de un nuevo manejador de eventos para controlar la lógica de selección/deselección
- No hay cambios significativos en el rendimiento
3. **UX/UI**:
- Mejora de la experiencia de usuario permitiendo deshacer selecciones
- Mayor flexibilidad para los usuarios al completar cuestionarios
- Reducción de frustración al poder rectificar selecciones incorrectas
4. **Refactorización**:
- Simplificación del manejo de eventos de selección
- Mejora de la …
=> Deseleccionar preguntas 

dev-dist/sw.js, src/data/asignaturas/programacion/index.js, src/data/asignaturas/programacion/modulos/simulacroVirtualLab.js
Añadir un nuevo módulo de simulacro para evaluación de conceptos de Java, que incluye 40 preguntas de examen con diferentes niveles de dificultad, recursos de código y explicaciones detalladas.
- **Módulos añadidos**: 1 (Simulacro Virtual Lab 13/05/2025)
- **Preguntas añadidas**: 40
- **Recursos implementados**: 9 bloques de código en Java
1. **Nuevo módulo de "Simulacro Virtual Lab (13/05/2025)"**
- Implementación de un examen simulacro con 40 preguntas sobre Java
- Cubre conceptos como excepciones, estructuras de datos, clases, interfaces, POO
- Contiene preguntas con bloques de código que evalúan la comprensión práctica
- Cada pregunta incluye explicación detallada de la respuesta correcta
2. **Implementación de recursos**
- 9 bloques de código en Java …
=> Añadir el simulacro 2 de Raúl Programación VL

src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen02.js
- Un convenio colectivo indica el cómputo total de horas a trabajar siempre que respete el total de 40h legales.
- La jornada puede distribuirse de manera irregular. El jefe tiene derecho a alterar un 10% la jornada laboral si no se está de acuerdo con esta distribución irregular.
- Descansos:
- Durante la jornada: 15min si excede de 6h, 30 min si excede de 6,5h y eres menor. 
- Entre jornada: 12h. 
- Entre semanas: Día y medio ininterrupido (para menores 2).
- (PREGUNTA) Trabajo nocturno: 
- de 22h a 06h,
- si trabajas 3h en ese horario, 
- si trabajas 1/3 en ese horario.
- Reducción de jornada por guardia legal: niño menor de 12 años.
- Reducción de jornada por cuidado de familiar: hasta 2º grado de consanguinidad/afinidad (NOTA: a fectos de la legislación laboral, casi todas las …
=> feat(importanteExamen.js): añadidas preguntas del tema 6. Bloque completado

SECURITY.md, dev-dist/sw.js, package.json, src/App.jsx, src/components/common/FavoriteButton.jsx, src/components/common/Toast.jsx, src/components/common/ToastContainer.jsx, src/components/common/index.js, src/components/quiz/FavoriteButton.jsx, src/components/quiz/FavoriteQuizzes.jsx, src/components/quiz/FavoritesQuizLoader.jsx, src/components/quiz/QuestionCard.jsx, src/components/quiz/QuestionReview.jsx, src/components/quiz/QuizContent.jsx, src/components/quiz/index.js, src/context/QuizProvider.jsx, src/pages/HomePage.jsx, src/pages/QuizPage.jsx, src/pages/ResultsPage.jsx, src/services/favoritesService.js, src/utils/quizConstants.js, src/utils/toastUtils.js
Este PR implementa dos mejoras principales:
1. **Centralización del sistema de notificaciones (Toast)**
2. **Creación e implementación completa del sistema de favoritos**
- Eliminación de duplicación de código (`ToastContainer` repetido en múltiples páginas)
- Unificación de la experiencia de notificaciones en toda la aplicación
- Simplificación del mantenimiento y configuración de notificaciones
- **App.jsx**: Añadido `ToastContainer` centralizado
- **QuizPage.jsx**: Eliminado `ToastContainer` duplicado
- **ResultsPage.jsx**: Eliminado `ToastContainer` duplicado
- **toastUtils.js**: Optimizado para trabajar con contenedor centralizado
- **ToastContainer.jsx**: Mejorado para funcionar como contenedor global
El sistema ahora funciona de la siguiente manera:
1. Un único `ToastContainer` se …
=> Añadir sistema de Favoritos

dev-dist/sw.js, src/data/asignaturas/programacion/index.js, src/data/asignaturas/programacion/modulos/simBloqueOcho.js
Añadido el simulacro de examen del Bloque 8 de Programación
- **Módulos añadidos**: 1
- **Preguntas añadidas**: 17
- **Recursos implementados**: 0
1. Nuevo módulo de Programación
- Nuevas preguntas para el módulo de Bloque 8
- Examen centrado en el manejo de errores y excepciones en Java. Se evaluarán conceptos como try-catch, jerarquía de excepciones y buenas prácticas en el control de flujo mediante excepciones.
2. Implementación de recursos
- En lugar de imágenes, código para algunas preguntas específicas
- 
3. Organización del contenido
- Preguntas organizadas secuencialmente del ID 31301 al 31317
- Explicaciones para cada respuesta
```
src/data/asignaturas/programacion/
├── modulos/
│   ├── simBloqueOcho.js
├── info.js
└── index.js
```
```js
// Ejemplo …
```
=> Añadir módulo simulacro Bloque 8 Programación

SECURITY.md, dev-dist/sw.js, package.json, src/data/asignaturas/basesDeDatos/index.js, src/data/asignaturas/basesDeDatos/modulos/moduloSimulacroTres.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadOcho.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadSiete.js, src/data/asignaturas/lenguajeDeMarcas/index.js, src/data/asignaturas/lenguajeDeMarcas/modulos/simulacroTresLenguajeDeMarcas.js, src/data/asignaturas/programacion/index.js, src/data/asignaturas/programacion/modulos/simBloqueSeis.js, src/pages/QuizPage.jsx, src/utils/toastUtils.js
Se añaden cuatro nuevos módulos educativos: dos simulacros de examen (Bases de Datos y Lenguaje de Marcas) y dos unidades de teoría para la asignatura de ITP (Unidades 7 y 8). Estos módulos complementan el material educativo existente con contenido actualizado y alineado con el temario de mayo 2025.
- **Módulos añadidos**: 4 ("Simulacro 3 (14/05/2025) REMIX 1-2", "Simulacro de examen de Lenguaje de Marcas 2 (10/05/2025) REMIX 1-2", "Test Unidad 7", "Test Unidad 8")
- **Preguntas añadidas**: 126 (40 + 40 + 21 + 25)
- **Recursos implementados**: Bloques de código SQL y ejemplos de sintaxis
1. **Nuevo módulo de Simulacro de examen para Bases de Datos**
- 40 preguntas sobre SQL, consultas, permisos y backups
- Enfoque en consultas avanzadas, subconsultas, …
=> Añadir Modulos Lenguaje De Marco , Bases de Datos e ITP

dev-dist/sw.js, package-lock.json, src/App.jsx, src/components/common/Button.jsx, src/components/common/FavoriteButton.jsx, src/components/layout/ThemeToggle.jsx, src/components/quiz/ModuleSelector.jsx, src/components/quiz/QuestionNavigator.jsx, src/components/quiz/SubjectSelector.jsx
Los botones no mostraban un efecto cursor pointer en hover.
Fixes #91
El problema ocurría en varios botones de la aplicación.
Hemos añadido una clase tailwind a la clase base de los botones. También hemos detectado botones mal implementados y los hemos reemplazado por el componente Button.
Todos los botones de la app ahora son fácilmente identificables.
- **Componentes afectados**:  Todos los botones
1.  Hacer hover en un botón
1.  Hacer hover en un botón
=> fix: fixed cursor pointer in all buttons

src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/importanteExamen02.js
Se han añadido 4 preguntas sobre el SMAC:
- **Negociación**: es un proceso en el cual las partes implicadas en el conflicto intentan llegar a un acuerdo de forma directa, sin la intervención de terceros. En el ámbito laboral, esto puede suceder entre empleadores y trabajadores o sus representantes (sindicatos).
- **Conciliación**: es un proceso en el que ambas partes en conflicto (trabajador y empleador) se reúnen con alguien neutral que facilita el diálogo y la negociación para alcanzar un acuerdo amistoso.
- **Mediación**: un procedimiento en el que una persona imparcial ayuda a las partes a identificar sus intereses y a encontrar una solución aceptable para ambos, sin imponer una decisión.
- **Arbitraje**: es un proceso en el que una persona o grupo, que actúa como un tercero neutral, …
=> feat(importanteExamen02.js): Añadidas preguntas sobre SMAC. IDs corregidos

src/data/asignaturas/programacion/modulos/simBloqueSeis.js
Corrección de error de contenido en pregunta sobre métodos de Queue en Java
Fixes #312
La pregunta utilizaba el término "insertar()" en español para referirse a los métodos de inserción en una cola (Queue) de Java, lo que podría causar confusión ya que la API de Java utiliza métodos como "add()" y "offer()".
Actualizar la pregunta y explicación para utilizar la terminología correcta de Java, reemplazando "insertar()" por "add()" y aclarando en la explicación que también existe el método "offer()" y que conceptualmente esta operación se conoce como "enqueue()". Esto proporciona mayor claridad y alineación con la API de Java.
El problema fue causado por:
Una traducción literal de conceptos teóricos de estructuras de datos sin adaptarlos a …
=> Arreglos respuestas de colecciones ximo

dev-dist/sw.js, src/components/quiz/QuestionCard.jsx
1. **UX/UI**:
-  He implementado que cuando estás haciendo un test, se te cambie el cursor por un pointer al hacer hover sobre una opción, para que sea mas intuitivo que tienes el elegir una opción.
Archivo modificado:
- QuestionCard.jsx
- **Líneas añadidas**:  0
- **Líneas eliminadas**: 0
- **Archivos modificados**: 1
1.  Pasar el ratón por encima de una de las opciones del tipo test
- **Nuevas dependencias**:  0
- **Cambios en configuración**:  0
- **Posibles efectos secundarios**:  Ninguno
=> fix:anadir hover a opciones preguntas

src/components/common/CodeBlock.jsx, src/components/common/index.js, src/components/quiz/QuestionCard.jsx, src/components/quiz/QuestionReview.jsx
Se ha añadido un botón para copiar código al portapapeles en los bloques de código de los componentes `QuestionCard` y `QuestionReview`. Para lograr esto, se ha creado un componente reutilizable `CodeBlock` que encapsula esta funcionalidad mientras mantiene el estilo visual existente.
- Creación de un nuevo componente reutilizable `CodeBlock`
- Refactorización de los componentes existentes para utilizar el nuevo componente
- Mantenimiento de la estructura visual y comportamiento existentes
- No hay cambios significativos en rendimiento
3. **UX/UI**:
- Añadido un botón intuitivo para copiar código con feedback visual (cambia de color e icono)
- Notificación toast para informar al usuario cuando el código ha sido copiado
- Adaptación del botón para …
=> Añadir botón de copia de código

SECURITY.md, dev-dist/sw.js, package-lock.json, package.json, src/components/quiz/FavoriteQuizzes.jsx, src/components/quiz/PDFGenerator.jsx, src/components/quiz/PendingQuizzes.jsx, src/components/quiz/index.js, src/context/QuizProvider.jsx, src/hooks/quiz/useQuizDialog.js, src/hooks/quiz/useQuizLoader.js, src/hooks/quiz/useQuizProgress.js, src/pages/QuizPage.jsx, src/pages/ResultsPage.jsx
Se ha implementado la funcionalidad para exportar a PDF tanto las preguntas favoritas como los resultados de exámenes. Esto permite a los usuarios descargar estos materiales para estudio offline o para mantener un registro de su progreso. Se ha utilizado la biblioteca `@react-pdf/renderer` para generar documentos PDF profesionales y consistentes que incluyen preguntas, respuestas, explicaciones e incluso recursos visuales y bloques de código.
Adicionalmente, se ha corregido un bug crítico donde el localStorage de tests pendientes y tests favoritos entraba en conflicto, causando comportamientos inesperados en la aplicación y pérdida potencial de datos guardados por el usuario.
- Creación de un nuevo componente reutilizable `PDFGenerator` para manejar la generación de …
=> Añadir Sistema de descarga de preguntas en PDF 

SECURITY.md, dev-dist/sw.js, package.json, src/components/quiz/favorites/FavoriteButton.jsx, src/data/asignaturas/itinerarioParaLaEmpleabilidad/index.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/legislacionYPrevencion.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/repasoUnidadCuatro.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/repasoUnidadDos.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/repasoUnidadTres.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/repasoUnidadUno.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadCinco.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadCuatro.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadDos.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadOcho.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadSeis.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadSiete.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadTres.js, src/data/asignaturas/itinerarioParaLaEmpleabilidad/modulos/unidadUno.js
Implementación de 4 nuevos módulos de repaso para la asignatura "Itinerario para la Empleabilidad", cubriendo las unidades 1-4 con preguntas detalladas y explicaciones técnicas comprensivas sobre prevención de riesgos laborales y derecho del trabajo.
- **Módulos añadidos**: 4 (repasoUnidadUno, repasoUnidadDos, repasoUnidadTres, repasoUnidadCuatro)
- **Preguntas añadidas**: 54 (10 + 10 + 20 + 14)
- **Recursos implementados**: Referencias normativas detalladas (LPRL, RSP, INSST, Código Civil, ET)
1. **Módulo de Repaso Unidad 1 - Fundamentos de PRL**
- 10 preguntas sobre conceptos básicos de prevención de riesgos laborales
- Cubre accidentes de trabajo, enfermedades profesionales, derechos y obligaciones
- Incluye definiciones de la OMS y clasificación de daños …
=> Añadir Test de Repaso ITP faltantes

SECURITY.md, dev-dist/sw.js, package.json, src/data/asignaturas/basesDeDatos/index.js, src/data/asignaturas/basesDeDatos/modulos/examenBasesDatos.js
Se añade el examen de base de datos realizado el fin de semana del 16 de mayo
- **Módulos añadidos**: 1-Examen Bases de Datos
- **Preguntas añadidas**: 40 
- **Recursos implementados**:  Código SQL
=> Añadir Examen Bases de Datos

SECURITY.md, dev-dist/sw.js, package.json, src/data/asignaturas/entornosDeDesarrollo/index.js, src/data/asignaturas/entornosDeDesarrollo/modulos/examenEntornos.js, src/data/asignaturas/entornosDeDesarrollo/modulos/simulacroEntornosTres.js, src/data/asignaturas/lenguajeDeMarcas/modulos/simulacroDosLenguajeDeMarcas.js
*Añadido de módulos de simulacro y examen final para la asignatura de Entornos de Desarrollo, proporcionando contenido evaluativo completo con explicaciones detalladas.*
**
**
- **Módulos añadidos**: *3 (Simulacro 2, Simulacro 3 y Examen Final para Entornos de Desarrollo)*
- **Preguntas añadidas**: *120 (40 preguntas por cada módulo)*
- **Recursos implementados**: *Código JavaScript estructurado*
**
1. **Nuevos módulos para la asignatura de Entornos de Desarrollo**
- Simulacro 2 (ID: 507): Módulo con 40 preguntas que abarca UML, entornos de desarrollo, control de versiones, pruebas y mantenimiento de software.
- Simulacro 3 (ID: 508): Módulo con 40 preguntas que complementa al simulacro anterior con variantes de contenido similar.
- Examen Final (ID: 509): …
=> Añadir modulos Entornos 

dev-dist/sw.js, src/data/asignaturas/programacion/index.js, src/data/asignaturas/programacion/modulos/simBloqueDiez.js, src/data/asignaturas/programacion/modulos/simBloqueNueve.js, src/data/asignaturas/programacion/modulos/simulacroVirtualLabDos.js
*Adición de módulos de examen para el Bloque 9 y Bloque 10 (Servicios en Red y Acceso a Datos en Java) con sus respectivas preguntas de evaluación*
**
**
- **Módulos añadidos**: *2 - "Servicios en Red (Bloque 9)" y "Acceso a Datos (Bloque 10)"*
- **Preguntas añadidas**: *12 preguntas (6 por cada bloque)*
- **Recursos implementados**: *Código JavaScript para el módulo*
**
1. **Nuevos módulos de examen**
- **Bloque 9 - Servicios en Red**:
- Módulo de examen enfocado en conceptos de servicios en red, protocolos y arquitecturas cliente-servidor
- Objetivos de aprendizaje: Evaluar conocimientos sobre arquitecturas de red, protocolos de comunicación, sockets
- **Bloque 10 - Acceso a Datos**:
- Módulo de examen enfocado en conceptos de acceso a datos en Java
- …
=> feat:anadir bloques 9 10 a programacion

src/data/asignaturas/programacion/modulos/examenDAM.js
La opción de respuesta correcta de la pregunta 31806 del módulo 318 de Programación estaba mal apuntada 
Modificar el index de la opción conrrecta pasando de 0 a 1
=> Error respuesta de pregunta 31806

SECURITY.md, dev-dist/sw.js, package.json, src/data/asignaturas/sistemasInformaticos/index.js, src/data/asignaturas/sistemasInformaticos/modulos/simulacroCuatroSistemas.js, src/data/asignaturas/sistemasInformaticos/modulos/simulacroTresSistemas.js
*Añadidos dos nuevos módulos de simulacros para la asignatura de Sistemas Informáticos, correspondientes al Simulacro 3 y Simulacro 4, con un total de 80 preguntas que cubren conceptos fundamentales de hardware, redes, comandos Linux y administración de sistemas.*
*Marca con una "x" la opción relevante*
*Completa según corresponda*
- **Módulos añadidos**: *2 (Simulacro 3 - ID 106, Simulacro 4 - ID 107)*
- **Preguntas añadidas**: *80 preguntas (40 por simulacro)*
- **Recursos implementados**: *Explicaciones detalladas para cada pregunta, conversiones matemáticas, ejemplos prácticos*
*Describe detalladamente los cambios, siguiendo un formato similar a este:*
1. **Nuevo módulo Simulacro 3 (ID: 106)**
- 40 preguntas sobre hardware, redes IPv4/IPv6, comandos …
=> Añadir simulacros 3 y 4 de Sistemas informáticos 

dev-dist/sw.js, package-lock.json, src/data/asignaturas/entornosDeDesarrollo/index.js, src/data/asignaturas/entornosDeDesarrollo/modulos/examenEntornosDos.js
Añadir módulo "Examen Final 2 - Entornos de Desarrollo" con 42 preguntas que cubren todos los contenidos de la asignatura, incluyendo dos preguntas adicionales (41 y 42) explicadas por JM en clase sobre trazabilidad de requisitos y ciclo de vida del software.
- **Módulos añadidos**: 1 (Examen Final 2 - Entornos de Desarrollo)
- **Preguntas añadidas**: 42 (incluyendo 2 preguntas adicionales explicadas en clase)
- **Recursos implementados**: Explicaciones detalladas para cada pregunta
1. **Nuevo módulo de Examen Final 2 - Entornos de Desarrollo**
- 42 preguntas que abarcan: diagramas UML, control de versiones con Git, ciclo de vida del software, virtualización, lenguajes de programación, técnicas de pruebas y mantenimiento
- Corrección de errores tipográficos …
=> Añadir Examen 2 Entornos

dev-dist/sw.js, src/data/asignaturas/lenguajeDeMarcas/index.js, src/data/asignaturas/lenguajeDeMarcas/modulos/examenLenguaje.js
Se añade el módulo "Examen de Lenguaje de Marcas " con 43 preguntas que cubren todos los aspectos fundamentales del desarrollo web frontend, incluyendo HTML5, CSS3, Flexbox, CSS Grid, Bootstrap, JavaScript, FileReader y localStorage.
- **Módulos añadidos**: 1 - "Simulacro de examen de Lenguaje de Marcas 4 (Examen Final)" (ID: 413)
- **Preguntas añadidas**: 43 preguntas (IDs: 41301-41343)
- **Recursos implementados**: Explicaciones detalladas para cada pregunta con ejemplos prácticos
1. **Nuevo módulo de Simulacro de Examen Final**
- Módulo integral que evalúa conocimientos completos de desarrollo web frontend
- Cubre HTML5 semántico, CSS3 avanzado, sistemas de layout modernos y JavaScript
- Incluye evaluación de frameworks como Bootstrap y APIs del navegador …
=> Añadir Examen lenguaje de marcas
